# application.yml (공통 설정)
spring:
  profiles:
    active: dev  # 활성화할 프로파일을 dev로 설정

  jpa:
    hibernate:
      ddl-auto: update  # DB 자동 생성 및 수정
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect 설정

  servlet:
    multipart:
      max-file-size: 10MB  # 최대 파일 크기
      max-request-size: 10MB  # 최대 요청 크기

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # URL 경로 매칭 전략

server:
  port: 8080  # 서버 포트 설정
  devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
      thymeleaf:
        cache: false

jwt:
  secret: my-super-secret-jwt-key  # JWT 비밀키
  expiration: 3600000  # JWT 만료 시간 (1시간, ms 단위)

springdoc:
  api-docs:
    path: /api-docs  # Swagger API Docs 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # DB 컬럼명을 카멜케이스로 변환