# application-dev.yml (개발 환경 설정)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizify?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root22
    password: h222  # 개발 DB 설정
  jpa:
    hibernate:
      ddl-auto: update  # DB 자동 생성 및 수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect 설정

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false  # 캐시 비활성화

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # MyBatis 매퍼 XML 경로
  configuration:
    map-underscore-to-camel-case: true  # DB 컬럼명을 카멜케이스로 변환